name: InfiniteBlock
main: ifteam\InfiniteBlock\InfiniteBlock
version: 0.9-alpha
author: ifteam
api:
- 1.4.1
- 1.12.0
- 1.13.0
- 2.0.0
- 3.0.0-ALPHA1

permissions:
 infinite:
  default: op
 infinite.VIP:
  default: op
